name = "pax-frontend"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
# Añade tus variables de entorno aquí
# NEXT_PUBLIC_API_URL = "https://tu-api.com"
